const $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d'),W=1400,H=560;
let terrain=[],tanks=[],shot=null,particles=[],turn=0,turns=1,round=0,wind=6,phase='aim',timer=0,muted=true,audioContext,seed=0;
const weapons={shell:{radius:43,damage:48,name:'Standard shell'},heavy:{radius:70,damage:68,name:'Heavy shell'},nuke:{radius:115,damage:100,name:'Mini nuke'}};
const rand=(a,b)=>a+Math.random()*(b-a);
function ground(x){return terrain[Math.max(0,Math.min(W,Math.round(x)))];}
function sound(freq,duration){if(muted)return;audioContext??=new (window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.setValueAtTime(freq,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(30,audioContext.currentTime+duration);g.gain.setValueAtTime(.08,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.start();o.stop(audioContext.currentTime+duration);}
function reset(){clearTimeout(timer);round++;seed=rand(0,9);terrain=Array.from({length:W+1},(_,x)=>365+54*Math.sin(x*.006+seed)+27*Math.sin(x*.013+1+seed)+12*Math.cos(x*.023));tanks=[{name:'Nomad',role:'YOU / COMMANDER',color:'#d5ed8a',x:150},{name:'Viper',role:'AI / SHARPSHOOTER',color:'#cba078',x:510},{name:'Ghost',role:'AI / TACTICIAN',color:'#b3c1bd',x:890},{name:'Blaze',role:'AI / HEAVY HITTER',color:'#d38964',x:1240}].map(t=>({...t,hp:100,angle:t.x<700?45:135,power:65,heavy:3,nuke:1}));for(const t of tanks){const y=ground(t.x);for(let x=t.x-22;x<=t.x+22;x++)terrain[x]=y;}turn=0;turns=1;shot=null;particles=[];phase='aim';wind=Math.round(rand(-10,11));$('overlay').hidden=true;$('round-label').textContent=`ROUND ${String(round).padStart(2,'0')}`;$('angle').value=45;$('power').value=65;$('weapon').value='shell';update();}
function update(){const t=tanks[turn];$('angle-value').value=$('angle').value;$('power-value').value=$('power').value;$('wind').textContent=`WIND ${wind>=0?'→':'←'} ${Math.abs(wind)} KM/H`;$('turn-count').textContent=`TURN ${String(turns).padStart(2,'0')}`;const ready=turn===0&&phase==='aim';$('fire').disabled=!ready;for(const id of ['angle','power','weapon'])$(id).disabled=!ready;$('turn-badge').innerHTML=`<i></i> ${phase==='over'?'BATTLE COMPLETE':ready?'YOUR TURN':t.name.toUpperCase()+' / '+(phase==='flight'?'SHOT IN FLIGHT':'TAKING AIM')} <span>${ready?'Make it count.':'Hold position.'}</span>`;$('roster').innerHTML=tanks.map((t,i)=>`<div class="tank-card ${i===turn?'active':''} ${t.hp<=0?'dead':''}" style="--tank:${t.color}"><div class="card-top"><span class="tank-symbol">▰</span><div><div class="tank-name">${t.name}</div><div class="tank-role">${t.role}</div></div><span class="card-status">${t.hp<=0?'DESTROYED':i===turn?'● ACTIVE':'STANDING BY'}</span></div><div class="health-row"><div class="health-track"><div class="health-fill" style="width:${t.hp}%"></div></div><span>${t.hp}<span style="opacity:.5"> / 100</span></span></div></div>`).join('');for(const option of $('weapon').options){const key=option.value;option.disabled=key!=='shell'&&tanks[0][key]<=0;if(key!=='shell')option.textContent=`${weapons[key].name} · ${tanks[0][key]} left`;}
const key=$('weapon').value;$('weapon-detail').textContent={shell:'Reliable. Precise. Destructive.',heavy:'Bigger crater. Greater impact.',nuke:'One shot. A whole new landscape.'}[key];$('ammo').textContent=key==='shell'?'∞  UNLIMITED AMMO':`${tanks[0][key]}  ROUNDS REMAINING`;}
function projectile(t,angle,power){const a=angle*Math.PI/180,speed=power*8;return{x:t.x+Math.cos(a)*25,y:ground(t.x)-14-Math.sin(a)*25,vx:Math.cos(a)*speed,vy:-Math.sin(a)*speed};}
function step(p,dt){p.vx+=wind*2.6*dt;p.vy+=320*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}
function fire(){if(phase!=='aim')return;const t=tanks[turn],key=turn===0?$('weapon').value:(Math.random()<.24&&t.heavy>0?'heavy':'shell');if(key!=='shell')t[key]--;if(turn===0){t.angle=+$('angle').value;t.power=+$('power').value;}shot={...projectile(t,t.angle,t.power),key,trail:[],age:0};phase='flight';$('status').textContent=`${t.name} fired a ${weapons[key].name.toLowerCase()}.`;sound(180,.22);update();}
function blast(x,y,key){const w=weapons[key];for(const t of tanks){if(t.hp<=0)continue;const distance=Math.hypot(t.x-x,ground(t.x)-10-y);t.hp=Math.max(0,t.hp-Math.round(w.damage*Math.max(0,1-distance/(w.radius*1.6))));}for(let i=Math.max(0,Math.floor(x-w.radius));i<=Math.min(W,Math.ceil(x+w.radius));i++){const bottom=y+Math.sqrt(Math.max(0,w.radius*w.radius-(i-x)**2));terrain[i]=Math.min(H-20,Math.max(terrain[i],bottom));}for(const t of tanks){const drop=ground(t.x)-(t.lastY??ground(t.x));if(t.hp>0)t.hp=Math.max(0,t.hp-Math.round(Math.max(0,drop-20)*.42));}for(let i=0;i<65;i++)particles.push({x,y,vx:rand(-170,170),vy:rand(-230,90),life:rand(.4,1.2),max:1.2,size:rand(2,7),color:i%3?'#e5bf75':'#6d6040'});particles.push({x,y,vx:0,vy:0,life:.35,max:.35,size:w.radius,ring:true});sound(70,.65);shot=null;phase='settle';update();timer=setTimeout(nextTurn,1200);}
function nextTurn(){const alive=tanks.filter(t=>t.hp>0);if(alive.length<=1||tanks[0].hp<=0){phase='over';$('overlay').hidden=false;$('result').textContent=tanks[0].hp>0?'The badlands are yours.':'Outgunned. Not forgotten.';$('result-detail').textContent=tanks[0].hp>0?`Victory in ${turns} turns. A clean sweep through the dust.`:'Your tank was destroyed. Deploy again and find a better firing solution.';$('status').textContent='Battle complete. Start a new battle to play again.';update();return;}do{turn=(turn+1)%4;}while(tanks[turn].hp<=0);turns++;wind=Math.max(-15,Math.min(15,wind+Math.round(rand(-3,3))));phase='aim';$('status').textContent=turn===0?'Your move, Commander. Set your trajectory and fire.':`${tanks[turn].name} is calculating a firing solution…`;if(turn===0){$('angle').value=tanks[0].angle;$('power').value=tanks[0].power;if($('weapon').value!=='shell'&&tanks[0][$('weapon').value]===0)$('weapon').value='shell';}update();if(turn!==0)timer=setTimeout(ai,1000);}
function ai(){const t=tanks[turn],targets=tanks.filter(q=>q!==t&&q.hp>0),target=targets[Math.floor(Math.random()*targets.length)];let best={error:Infinity};for(let a=20;a<=160;a+=3)for(let power=25;power<=100;power+=2){let p=projectile(t,a,power);for(let n=0;n<600;n++){step(p,.025);if(p.x<0||p.x>W||p.y>H)break;if(p.y>=ground(p.x)){const error=Math.abs(p.x-target.x);if(error<best.error)best={error,angle:a,power};break;}}}t.angle=(best.angle??(target.x>t.x?45:135))+rand(-2,2);t.power=Math.max(10,Math.min(100,(best.power??65)+rand(-3,3)));fire();}
function mountain(color,base,amp,freq,offset){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,H);for(let x=0;x<=W;x+=6)ctx.lineTo(x,base+Math.sin(x*freq+offset)*amp+Math.sin(x*freq*2.7+offset)*amp*.3);ctx.lineTo(W,H);ctx.fill();}
function draw(){ctx.clearRect(0,0,W,H);const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#b9b6a0');sky.addColorStop(.65,'#d4bd8e');sky.addColorStop(1,'#ae9b70');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ded1a8';ctx.beginPath();ctx.arc(1030,115,43,0,Math.PI*2);ctx.fill();mountain('#aca68b',280,47,.004,2);mountain('#96937b',325,56,.007,4);mountain('#7e816a',360,39,.009,1);ctx.fillStyle='#4a523c';ctx.beginPath();ctx.moveTo(0,H);terrain.forEach((y,x)=>ctx.lineTo(x,y));ctx.lineTo(W,H);ctx.closePath();ctx.fill();ctx.strokeStyle='#777c54';ctx.lineWidth=3;ctx.beginPath();terrain.forEach((y,x)=>x?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();ctx.save();ctx.clip();for(let j=0;j<4;j++){ctx.beginPath();ctx.strokeStyle=j%2?'#414a35':'#565b40';ctx.lineWidth=1;for(let x=0;x<=W;x+=4){let y=ground(x)+35+j*43+Math.sin(x*.012+j)*12;x?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}for(let i=0;i<370;i++){const x=(i*79.37)%W,y=ground(x)+10+(i*33.73)%220;if(y<H){ctx.fillStyle=i%2?'#77785a55':'#252f2355';ctx.fillRect(x,y,2,1);}}ctx.restore();
for(const t of tanks){const y=ground(t.x);t.lastY=y;ctx.save();ctx.translate(t.x,y);if(t.hp<=0){ctx.fillStyle='#292c24';ctx.fillRect(-15,-8,30,8);ctx.restore();continue;}ctx.fillStyle='#242b22';ctx.beginPath();ctx.ellipse(0,2,24,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=t.color;ctx.fillRect(-17,-11,34,8);ctx.beginPath();ctx.roundRect(-20,-6,40,10,5);ctx.fill();ctx.fillStyle='#323c29';for(let i=-12;i<=12;i+=8){ctx.beginPath();ctx.arc(i,-1,3,0,7);ctx.fill();}ctx.fillStyle=t.color;ctx.beginPath();ctx.ellipse(0,-12,10,7,0,Math.PI,0);ctx.fill();const a=(turn===0&&t===tanks[0]?+$('angle').value:t.angle)*Math.PI/180;ctx.strokeStyle=t.color;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(Math.cos(a)*25,-13-Math.sin(a)*25);ctx.stroke();ctx.font='500 10px monospace';ctx.textAlign='center';ctx.fillStyle='#ece6cc';ctx.fillText(t.name.toUpperCase(),0,-48);ctx.fillStyle='#303a2b';ctx.fillRect(-20,-38,40,3);ctx.fillStyle=t.color;ctx.fillRect(-20,-38,t.hp*.4,3);if(t===tanks[turn]){ctx.fillStyle=t.color;ctx.beginPath();ctx.moveTo(-4,-66);ctx.lineTo(4,-66);ctx.lineTo(0,-60);ctx.fill();}ctx.restore();}
if(turn===0&&phase==='aim'){const p=projectile(tanks[0],+$('angle').value,+$('power').value);ctx.fillStyle='#f0ebc484';for(let i=0;i<20;i++){step(p,.065);if(p.x<0||p.x>W||p.y>=ground(p.x))break;ctx.beginPath();ctx.arc(p.x,p.y,1.8,0,7);ctx.fill();}}
if(shot){ctx.strokeStyle='#f6e7b899';ctx.lineWidth=2;ctx.beginPath();shot.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.shadowBlur=12;ctx.shadowColor='#ffe2a1';ctx.fillStyle='#fff2cc';ctx.beginPath();ctx.arc(shot.x,shot.y,4,0,7);ctx.fill();ctx.shadowBlur=0;}
for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);if(p.ring){ctx.fillStyle='#ffe8a1';ctx.beginPath();ctx.arc(p.x,p.y,p.size*(1-p.life/p.max),0,7);ctx.fill();}else{ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);}}ctx.globalAlpha=1;}
let last=0;function loop(now){const dt=Math.min((now-last)/1000,.035);last=now;if(shot){for(let i=0;i<3&&shot;i++){step(shot,dt/3);shot.age+=dt/3;if(shot.x<0||shot.x>W||shot.age>12){shot=null;phase='settle';$('status').textContent='Shot left the battlefield. Adjust your next firing solution.';timer=setTimeout(nextTurn,700);}else if(shot.y>=ground(shot.x)){blast(shot.x,ground(shot.x),shot.key);}}if(shot){shot.trail.push({x:shot.x,y:shot.y});if(shot.trail.length>90)shot.trail.shift();}}particles=particles.filter(p=>p.life>0);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=300*dt;}draw();requestAnimationFrame(loop);}
$('fire').onclick=()=>{if(turn===0)fire();};$('new-game').onclick=reset;$('play-again').onclick=reset;for(const id of ['angle','power','weapon'])$(id).addEventListener('input',update);$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=$('got-it').onclick=()=>$('help-dialog').close();$('sound').onclick=()=>{muted=!muted;$('sound').style.color=muted?'#babfaf':'#d5ed8a';$('sound').setAttribute('aria-pressed',String(!muted));sound(440,.15);};document.addEventListener('keydown',e=>{if($('help-dialog').open||turn!==0||phase!=='aim'||e.target.tagName==='SELECT')return;if(e.code==='Space'&&!['BUTTON','INPUT'].includes(e.target.tagName)){e.preventDefault();fire();}if(e.target.tagName==='INPUT')return;const map={ArrowLeft:['angle',1],ArrowRight:['angle',-1],ArrowUp:['power',1],ArrowDown:['power',-1]};if(map[e.key]){e.preventDefault();const[id,d]=map[e.key];$(id).value=+$(id).value+d;update();}});reset();requestAnimationFrame(loop);
